# Generated by Django 3.1.5 on 2021-02-07 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolkitexam',
            name='description',
        ),
        migrations.RemoveField(
            model_name='toolkitexam',
            name='name',
        ),
    ]
