# Generated by Django 3.1.5 on 2021-02-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0002_auto_20210207_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolkitexam',
            name='exam_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
