# Generated by Django 3.1.5 on 2021-02-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0003_auto_20210207_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolkitexam',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
