# Generated by Django 3.1.5 on 2021-02-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0005_auto_20210207_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolkitexam',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toolkitexam',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
