# Generated by Django 3.1.5 on 2021-03-09 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0008_auto_20210223_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolkitkubernetescleaner',
            name='resources',
        ),
    ]
