# Generated by Django 3.1.5 on 2021-03-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0009_remove_toolkitkubernetescleaner_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolkitingresswhitelist',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='toolkitingresswhitelist',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='toolkitkubernetescleaner',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='toolkitkubernetescleaner',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
