# Generated by Django 3.1.5 on 2021-03-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0012_auto_20210309_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolkitkubernetescleaner',
            old_name='pod',
            new_name='pods',
        ),
    ]
