# Generated by Django 3.1.5 on 2021-03-09 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('k8s', '0001_initial'),
        ('toolkit', '0013_auto_20210309_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolkitkubernetescleaner',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='k8s.kubernetescluster'),
        ),
    ]
