{{- if .Values.global.frontend.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.global.frontend.replicas }}
  selector:
    matchLabels:
        app: {{ .Release.Name }}
        type: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        type: frontend
    spec:
      containers:
      - name: {{ .Release.Name }}-frontend
        ports:
          - containerPort: {{ .Values.global.frontend.containerPort }}
            protocol: {{ .Values.global.frontend.protocol }}
        image:  {{ .Values.global.frontend.image.repository }}:{{ .Values.global.frontend.image.tag }}
        imagePullPolicy: {{ .Values.global.frontend.image.pullPolicy }}
      restartPolicy: Always
      imagePullSecrets:
      - name: aliyun-registry

    {{- with .Values.global.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
