apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
spec:
  ports:
  - name: http
    port: {{ .Values.service.backend.port }}
    protocol: {{ .Values.global.backend.protocol }}
    targetPort: {{ .Values.global.backend.containerPort }}
  selector:
    app: {{ .Release.Name }}
    type: backend
  type: {{ .Values.service.backend.type }}
---
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}-frontend
spec:
  ports:
  - name: http
    port: {{ .Values.service.frontend.port }}
    protocol: {{ .Values.global.frontend.protocol }}
    targetPort: {{ .Values.global.frontend.containerPort }}
  selector:
    app: {{ .Release.Name }}
    type: frontend
  type: {{ .Values.service.frontend.type }}
---
{{- if .Values.global.flower.enabled }}
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}-flower
spec:
  ports:
  - name: http
    port: {{ .Values.service.flower.port }}
    protocol: {{ .Values.global.flower.protocol }}
    targetPort: {{ .Values.global.flower.containerPort }}
  selector:
    app: {{ .Release.Name }}
    type: flower
  type: {{ .Values.service.backend.type }}
{{- end }}