{{- if .Values.global.worker.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
spec:
  replicas: {{ .Values.global.worker.replicas }}
  selector:
    matchLabels:
        app: {{ .Release.Name }}
        type: worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        type: worker
    spec:
      containers:
      - name: {{ .Release.Name }}-worker
        {{- if .Values.global.worker.command.enabled }}
        command: {{- toYaml .Values.global.worker.command.cmd | nindent 10}}
        {{- end }}
        env:
        {{- range  .Values.global.env }}
        - name: {{ index . "name" }}
          value: {{ toYaml (index . "value") | trim}}
        {{- end }}

        {{- if .Values.global.envFromSecret.enabled }}
        envFrom:
        {{- range .Values.global.envFromSecret.name }}
        - secretRef:
            name: {{ index . }}
        {{- end }}
        {{- end }}
        image:  {{ .Values.global.worker.image.repository }}:{{ .Values.global.worker.image.tag }}
        imagePullPolicy: {{ .Values.global.worker.image.pullPolicy }}
      restartPolicy: Always
      imagePullSecrets:
      - name: aliyun-registry

    {{- with .Values.global.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
