# Generated by Django 3.1.5 on 2021-03-30 09:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userProfile',
            new_name='profile',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='user_profile',
        ),
    ]
