# Generated by Django 3.1.5 on 2021-03-30 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210330_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='create_time',
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
