# Generated by Django 3.1.5 on 2021-02-26 09:36

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KubernetesCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'resource already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('description', models.CharField(blank=True, max_length=150)),
                ('displayname', models.CharField(blank=True, max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('api_endpoint', models.URLField(help_text='Cluster Endpoint URL')),
                ('config', models.JSONField(help_text='Equivalent to .kube/config but all JSON', null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='KubernetesDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'resource already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('labels', models.CharField(blank=True, max_length=1000)),
                ('annotations', models.CharField(blank=True, max_length=3000)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KubernetesNamespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'resource already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('labels', models.CharField(blank=True, max_length=1000)),
                ('annotations', models.CharField(blank=True, max_length=3000)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
