# Generated by Django 3.1.5 on 2021-03-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroperationlog',
            name='before',
            field=models.JSONField(help_text='json format.', null=True),
        ),
    ]
