# Generated by Django 3.1.5 on 2021-02-22 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('k8s', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('repo', models.CharField(max_length=50)),
                ('chart_dir', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('enabled', models.BooleanField(
                    blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=50)),
                ('log', models.CharField(blank=True, max_length=50)),
                ('env', models.CharField(blank=True, max_length=50)),
                ('args', models.CharField(blank=True, max_length=150)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('rollback', models.BooleanField(blank=True, default=False)),
                ('cluster', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='k8s.kubernetescluster')),
                ('service', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='deploy.service')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
