# Generated by Django 3.1.5 on 2021-02-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
