# Generated by Django 3.1.5 on 2021-02-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_release_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='value_file',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
