# Generated by Django 3.1.5 on 2021-02-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0006_auto_20210223_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='service',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
