# Generated by Django 3.1.5 on 2021-02-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0007_auto_20210223_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='value_file',
        ),
    ]
