# Generated by Django 3.1.5 on 2021-02-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0008_remove_service_value_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='env',
            new_name='namespace',
        ),
    ]
