# Generated by Django 3.1.5 on 2021-02-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0009_auto_20210223_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='revision',
            field=models.IntegerField(default=0),
        ),
    ]
