# Generated by Django 3.1.5 on 2021-02-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0010_auto_20210223_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='state',
            new_name='status',
        ),
    ]
