# Generated by Django 3.1.5 on 2021-02-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0011_auto_20210224_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='task_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
